{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "2f568ccb-4ba9-4e56-883f-efd26ff721ae",
   "metadata": {},
   "source": [
    "Q1. What is an Exception in python? Write the difference between Exceptions and syntax errors\n",
    "An error is an issue in a program that prevents the program from completing its task. In comparison, an exception is a condition that interrupts the normal flow of the program. Both errors and exceptions are a type of runtime error, which means they occur during the execution of a program\n",
    "Syntax error refers to an error in the syntax or structure of the code, meaning that the code is not written according to the rules of the programming language. These errors are usually caught by the compiler or interpreter before the code is executed, and they prevent the code from being compiled or run. For example, a missing semicolon at the end of a statement in JavaScript or a missing parenthesis in a function call in Python would result in a syntax error. On the other hand, an exception refers to an error that occurs during the execution of a program. These errors are not caught by the compiler or interpreter and can cause the program to terminate or behave unexpectedly. Exceptions can occur due to a variety of reasons, such as division by zero, trying to access an array element that does not exist, or attempting to open a file that does not exist.\n",
    "In summary, the main difference between syntax error and exception is that syntax errors are detected by the compiler or interpreter before the code is executed, while exceptions occur during the execution of the program.\n",
    "\n",
    "\n",
    "Q2. What happens when an exception is not handled? Explain with an example.\n",
    "When an exception occurred, if you don’t handle it, the program terminates abruptly and the code past the line that caused the exception will not get executed.\n",
    "Example\n",
    "Generally, an array is of fixed size and each element is accessed using the indices. For example, we have created an array with size 7. Then the valid expressions to access the elements of this array will be a[0] to a[6] (length-1).\n",
    "Whenever, you used an –ve value or, the value greater than or equal to the size of the array, then the ArrayIndexOutOfBoundsException is thrown.\n",
    "For Example, if you execute the following code, it displays the elements in the array asks you to give the index to select an element. Since the size of the array is 7, the valid index will be 0 to 6.\n",
    "\n",
    "\n",
    "Q3. Which Python statements are used to catch and handle exceptions? Explain with an example\n",
    "Try and except statements are used to catch and handle exceptions in Python. Statements that can raise exceptions are kept inside the try clause and the statements that handle the exception are written inside except clause.\n",
    "Example: Here we are trying to access the array element whose index is out of bound and handle the corresponding exception.\n",
    "Example \n",
    "a = [1, 2, 3]\n",
    "try: \n",
    "    print (\"Second element = %d\" %(a[1]))\n",
    "    print (\"Fourth element = %d\" %(a[3]))\n",
    "except:\n",
    "    print (\"An error occurred\")\n",
    "\n",
    "\n",
    "Q4. Explain with an example\n",
    "  \n",
    "a. try and else\n",
    "\n",
    "The code defines a function AbyB(a, b) that calculates c as ((a+b) / (a-b)) and handles a potential ZeroDivisionError. It prints the result if there’s no division by zero error. Calling AbyB(2.0, 3.0) calculates and prints -5.0, while calling AbyB(3.0, 3.0) attempts to divide by zero, resulting in a ZeroDivisionError, which is caught and “a/b results in 0” is printed.\n",
    "\n",
    "def AbyB(a , b):\n",
    "    try:\n",
    "        c = ((a+b) / (a-b))\n",
    "    except ZeroDivisionError:\n",
    "        print (\"a/b result in 0\")\n",
    "    else:\n",
    "        print (c)\n",
    "AbyB(2.0, 3.0)\n",
    "AbyB(3.0, 3.0)\n",
    "\n",
    "b. finally\n",
    "\n",
    "Python provides a keyword finally, which is always executed after the try and except blocks. The final block always executes after the normal termination of the try block or after the try block terminates due to some exception.\n",
    "\n",
    "try:\n",
    "    k = 5//0\n",
    "    print(k)\n",
    " \n",
    "except ZeroDivisionError:\n",
    "    print(\"Can't divide by zero\")\n",
    " \n",
    "finally:\n",
    "    print('This is always executed')\n",
    "\n",
    "c. raise\n",
    "\n",
    "The raise statement allows the programmer to force a specific exception to occur. The sole argument in raise indicates the exception to be raised. This must be either an exception instance or an exception class (a class that derives from Exception).\n",
    "This code intentionally raises a NameError with the message “Hi there” using the raise statement within a try block. Then, it catches the NameError exception, prints “An exception,” and re-raises the same exception using raise. This demonstrates how exceptions can be raised and handled in Python, allowing for custom error messages and further exception propagation.\n",
    "try: \n",
    "    raise NameError(\"Hi there\")\n",
    "except NameError:\n",
    "    print (\"An exception\")\n",
    "    raise\n",
    "\n",
    "\n",
    "Q.5 what are the custom exceptions in python? Why do we need custom exceptions? Explain with an example.\n",
    "Custom exceptions are helpful in many situations. They allow you to define your own error conditions and handle them in a more specific and meaningful way For example, let’s say you are writing a program that reads data from a file. If the file is not found, Python will raise a FileNotFoundError. However, this exception may not provide enough information to the user about what went wrong. In this case, you can define your own custom exception, such as FileNotFoundCustomError, which can provide more specific details about the error\n",
    "\n",
    "Custom exceptions are also useful in object-oriented programming, where you may want to define exceptions that are specific to your classes. For example, if you are creating a banking application, you may want to define an exception that is raised when a user tries to withdraw more money than they have in their account\n",
    "\n",
    "\n",
    "Q6. Create custom exception class. Use this class to handle an exception.\n",
    "Exceptions need to be derived from the Exception class, either directly or indirectly. Although not mandatory, most of the exceptions are named as names that end in “Error” similar to the naming of the standard exceptions in python. For example,\n",
    "\n",
    "# A python program to create user-defined exception\n",
    "# class MyError is derived from super class Exception\n",
    "class MyError(Exception):\n",
    " \n",
    "    # Constructor or Initializer\n",
    "    def __init__(self, value):\n",
    "        self.value = value\n",
    " \n",
    "    # __str__ is to print() the value\n",
    "    def __str__(self):\n",
    "        return(repr(self.value))\n",
    " \n",
    " \n",
    "try:\n",
    "    raise(MyError(3*2))\n",
    " \n",
    "# Value of Exception is stored in error\n",
    "except MyError as error:\n",
    "    print('A New Exception occurred: ', error.value)\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
